---
title: "Working with Goups of Series"
author: "Chris Hansen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Working with Groups of Series}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

<style type="text/css">
  .section.level1 h1 {
    font-size: 25px;
    line-height: 30px;
    margin-top: 20px;
    border-bottom: 6px solid #f7f7f7;
  }

.figure img{
  max-width: 80%;
}

.plotly.html-widget{
  width: 700px !important;
  padding-bottom: 10px;
}
</style>
  
```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE,
                      message = FALSE, comment = NA, 
                      fig.align = "center", 
                      fig.height = 4, fig.width = 5)
library(sadj)
```

## Overview

A single adjustable object has class `X13Series`.  We can also create a
collection of adjustable objects with a class of `X13SeriesGroup`.  This is
useful for adjusting multiple series in one step, and also permits the creation
of composite adjustments.
It is possible to group a number of `X13Series` objects together into a single
object, `X13SeriesGroup`, so that all series in the group can be adjusted at
the same time with a single call. 

This also makes it possible to use `X13-ARIMA-SEATS` `composite` specification
so that a series can be indirectly adjusted.  This is easier than forming
composites manually, but this way diagnostics are also provided for the
indirectly adjusted series, and one can compare directly the relative merits of
direct and indirect adjustments.

## A Simple Example

The package provides example series drawn from the Household Labour Force
Survey (HLFS).  We can use this to create several individual series&ndash;for
example, male and female unemployment:

```{R ex01}
memp <- X13Series(HLFS[HLFS$sname == "mlem",], sname = "memp")
setSpecParameter(memp, "series", "comptype") <- "add"

femp <- X13Series(HLFS[HLFS$sname == "fmle",], sname = "femp")
setSpecParameter(femp, "series", "comptype") <- "add"
```

This are simple X11-style adjustments, with `comptype` set to `add`.  We can
also create a simple composite for overall employment:

```{R ex02}
emp  <- X13Series(
  data.frame(memp[,1:2], value = memp[,3] + femp[,3]),
  sname = "emp",
  composite = list(title = "emp", save = "(isf isa itn b1 id8 iir)"),
  x11 = list(mode = "add", sigmalim = "(1.8,2.8)", save = "(e1 c17 d8 d9 d10 d11 d12 d13)")
)
```

We can then combine all 3 into a single adjustable object:

```{R ex03}
empgrp <- X13SeriesGroup("employment", memp, femp, emp)
```

We can then adjust the collection as usual:

```{R ex04}
empgrp.res <- adjust(empgrp)
```

The individual results can be extracted by name.  For example, to plot the
seasonal factors for the employed series (the composite):

```{R ex05}
plot(empgrp.res[["emp"]], type = "seasonal")
```






